version: 2.1
# Orb Dependencies
orbs:
  gcloud: circleci/gcp-cli@1.0.6
  gcr: circleci/gcp-gcr@0.0.2
  go: circleci/go@1.3.0

jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.14
    steps:
      - checkout
      - gcloud/install
      - gcloud/initialize
      - go/load-cache
      - go/mod-download
      - go/save-cache

      # Run tests
      - run:
          name: Run tests
          command: |
            go vet ./...
            go test ./...

      # Deploy app
      - run:
          name: Deploying app
          command: |
            if [[ $CIRCLE_BRANCH == master ]] ; then
              BUILD_NUM=<< pipeline.number >>
              echo "Deploying app"
              sudo apt-get install google-cloud-sdk-app-engine-go
              gcloud app deploy --project $GOOGLE_PROJECT_ID -q
            else echo "Not executing on a branch other than master"
            fi

workflows:
  version: 2.1
  main:
    jobs:
      - build:
            context: Deployment
